In [1]:
import numpy as np


In [8]:
numbers = np.arange(0,10)
print(numbers)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
boolchar = print(np.full((3,3), True, dtype = bool))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [28]:
odd = np.array([1,2,3,4,5,6,7,8,9,10])
odd[odd % 2==1]

array([1, 3, 5, 7, 9])

In [42]:
odd1 = np.arange(0,9)
odd1[1::2]




array([1, 3, 5, 7])

In [44]:
odd1[1::2] = -1
odd1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

In [59]:
matrixx = np.array([0,1,3,5,7,2,4,6,8,10])
print(matrixx)
reshapematr = np.reshape(matrixx, (2,5))
print(reshapematr)

[ 0  1  3  5  7  2  4  6  8 10]
[[ 0  1  3  5  7]
 [ 2  4  6  8 10]]


In [62]:
a = np.arange(1,5)
b = np.arange(1,5)
c = np.dot(a,b)
d = np.sum(c)
print(d)

30


In [80]:
extension = 'homework'


ext1 = np.repeat(a = [1,2,3] , repeats = 3)

ext11 = np.array(ext1 )
print(ext11)

[1 1 1 2 2 2 3 3 3]


In [102]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

print(np.unique(a, b))
              

ValueError: ignored

In [113]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8,9])

a.resize(b.shape)

np.add(a,b)


array([ 5,  7,  9, 11, 13,  9])